### ISSUE TITLE
Some options appear as if they are ignored

### ISSUE THREAD

**Issue by smikkelsen** [jfelchner/ruby-progressbar#119] opened 2016-11-09 02:41 UTC
I am unable to get a few option args to do anything. At least format, and remainder_mark options do nothing for me.

`pb = ProgressBar.create(total: total, remainder_mark: '-', format: '%a |%b>>%i| %p%% %t')`

Also, even on the default format, the end | doesn't show. I have not been successful at getting that to display (partially because format option seems to be completely ignored)

The final | shows up after the progress bar completes, but that is it.

`total = 100
    pb = ProgressBar.create(total: total, remainder_mark: '-', format: '%a |%b>>%i| %p%% %t')
    total.times do
      pb.increment
      sleep 0.01
    end`

**Comment by TimSmith714** [comment] 2016-11-21 15:59
I've had a similar problem - but not in every Ruby environment - when I was trying out the PacMan formatting example. (Though that turned out to be fixed by using " rather than ' when using the \u{FF65} character codes.

I was working with Komodo 9 and running in the built in debugger with Ruby 2.0. Running the script below it would ignore the formatting options.
So I tried on Ubuntu Server 14.04 with Ruby 2.0 and it did work.
I went back to Windows and tried running at the command prompt with "ruby progressTest.rb" and it worked!

So for me it looks like a problem (or bad setting) in Komodo

My test file

`require 'ruby-progressbar'
puts RUBY_VERSION
progressbar = ProgressBar.create( :total => 100, :format => '%a %bC%i %p%% %t', progress_mark => ' ', :remainder_mark => "\u{FF65}")
100.times {
progressbar.increment
sleep(0.5)
}
`

**Comment by jfelchner** [comment] 2016-11-21 18:34
@smikkelsen @TimSmith714 I'm very doubtful that this is a problem with `ruby-progressbar`.  I'm going to need some a reproducible test case to even be able to track it down.  All the code samples work just fine for me.

**Comment by jfelchner** [comment] 2016-12-10 22:38
@smikkelsen I'm going to close this.  I'd love to see a PR if you all can give me a definitive idea of what's causing the problem for you all.

**Closed by jfelchner** 2016-12-10 22:38 UTC

**Comment by smikkelsen** [comment] 2016-12-13 19:16
@jfelchner Sorry for the delay on this. I'm suspicious based on @TimSmith714 comments above that my issue might be related to Rubymine and/or the built in debugger. I haven't touched that project in a month or so, and haven't had a chance to go back and test the script in another environment. Closed is fine for now, and i'll assume its related to the debugger till i have time to dig deeper. 

Thanks!
