### ISSUE TITLE
cannot load such file -- enumerator (LoadError)

### ISSUE THREAD

**Issue by luk4s** [jfelchner/ruby-progressbar#175] opened 2022-05-24 09:53 UTC
`ruby-progressbar` in combination with others gems requiring `enumerator.rb` file cause error
```
cannot load such file -- enumerator (LoadError)
```
if they are loaded in specify order.

### Steps to Reproduce

In our application we have several dependencies
* https://rubygems.org/gems/ruby-msg
* https://rubygems.org/gems/roo-xls
which require "enumerator" for some reasons.

One of our gem require "ruby-progressbar" and by accident its named is alphabetically **before** ruby-msg.
Application is not able to start because error `cannot load such file -- enumerator (LoadError)` on ruby 3+ (tested, but I think 2.7+, because https://bugs.ruby-lang.org/issues/10902)

Expected Behavior
--------------------------------------------------------------------------------

**Comment by jfelchner** [comment] 2022-06-20 20:29
@luk4s I'm going to need a sample program to reproduce this.  There is no reason why calling `require "enumerator"` should load the refinement from this library.  The only thing that would load this refinement is `require "ruby-progressbar/refinements/enumerator"`.  That file is not even loaded by default and must be called explicitly.

**Comment by jfelchner** [comment] 2023-02-26 17:15
I now know what's going on here.  I'm closing this in favor of the [PR](#176).

**Closed by jfelchner** 2023-02-26 17:15 UTC

**Comment by luk4s** [comment] 2023-02-27 11:24
Hi @jfelchner  I prepared for you copy of our application with additional gems which cause it this order error, check our repo pls.
https://git.easy.cz/redmine/package/-/tree/progressbar_test_enumerator

**Comment by jfelchner** [comment] 2023-03-01 19:06
@luk4s I release 1.13.0rc1.  You will have to explicitly require it in your app because it's a non-stable version (`gem 'ruby-progressbar', '~> 1.13.0rc1'`)

Please let me know if this resolves the issue.

**Comment by luk4s** [comment] 2023-03-01 19:53
✅ I can confirm that `v1.13.0rc1` works - it did not cause "enumerator error" 👍 good job

Thank you

**Comment by jfelchner** [comment] 2023-03-01 20:52
Thank _you!_ ❤️
